
obj-$(CONFIG_KOWALSKI_FAST_CHARGE)		+= fastchg.o
obj-$(CONFIG_KOWALSKI_WIFI_PM)			+= wifipm.o
obj-$(CONFIG_KOWALSKI_CPU_CONTROL)		+= cpu_control.o
obj-$(CONFIG_KOWALSKI_AUTO_HOTPLUG)		+= auto_hotplug.o
obj-$(CONFIG_KOWALSKI_DYNAMIC_FSYNC)	+= dyn_fsync.o
obj-$(CONFIG_KOWALSKI_UV)				+= uv_config.o
obj-$(CONFIG_KOWALSKI_KNOCK_KNOCK)		+= knock_knock.o
